name: C++ CI with Coverage (Linux)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ lcov

    - name: Clean build folder
      run: rm -rf build

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage -O0 -g"

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

    - name: Generate coverage report
      run: |
        lcov --directory build --capture --output-file coverage.info --ignore-errors mismatch
        lcov --remove coverage.info '/usr/*' '*/googletest/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.info
