name: C++ CI with Coverage (Linux)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake lcov

    - name: Clean build dir
      run: rm -rf build

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage"

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ./build/runTests

    - name: Generate coverage report (.info)
      run: |
        lcov --directory build --capture --output-file coverage.info --ignore-errors mismatch
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Generate HTML report
      run: genhtml coverage.info --output-directory coverage_html

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage_html
